# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='name',
            field=models.CharField(default='addme', max_length=250),
            preserve_default=False,
        ),
    ]
