version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.gitlab.com/kerobot-dev/meowbot
    depends_on:
      - "db"
    ports:
      - "80:8000"
    volumes:
      - .:/app
    links:
      - db 
    tty: true
    command: dockerize -wait tcp://db:3306  python manage.py runserver 0.0.0.0:8000
    env_file: ./env_file.env
    volumes:
      - .:/app
  bot:
    image: registry.gitlab.com/kerobot-dev/meowbot
    depends_on:
      - "web"
      - "db"
    links:
      - db
    tty: true
    command: dockerize -wait tcp://db:3306  python meowbot.py
    restart: on-failure
    env_file: ./env_file.env
    volumes:
      - .:/app
  db:
    image: centurylink/mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    env_file: ./env_file.env
