# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catnip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catnip',
            name='currentAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
