# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomDrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BD', 'Body'), ('WH', 'Wheel'), ('BO', 'Boost'), ('AN', 'Antenna'), ('DE', 'Decal'), ('TO', 'Topper')], default='BD', max_length=2)),
                ('type_special', models.CharField(choices=[('P', 'Painted'), ('N', 'Normal'), ('C', 'Certified')], default='N', max_length=1)),
                ('colour', models.CharField(choices=[('ST', 'Standard'), ('BL', 'Black'), ('BS', 'Burnt Sienna'), ('CO', 'Cobalt'), ('CR', 'Crimson'), ('FG', 'Forest Green'), ('GR', 'Grey'), ('LI', 'Lime'), ('OR', 'Orange'), ('PI', 'Pink'), ('PU', 'Purple'), ('SA', 'Saffron'), ('SB', 'SkyBlue'), ('TW', 'Titanium White')], default='ST', max_length=2)),
                ('CertType', models.CharField(choices=[('NO', 'Notcert'), ('AC', 'Acrobat'), ('Av', 'Aviator'), ('GK', 'Goalkeeper'), ('GU', 'Guardian'), ('JU', 'Juggler'), ('PL', 'Playmaker'), ('SC', 'Scorer'), ('SO', 'ShowOff'), ('SN', 'Sniper'), ('ST', 'Striker'), ('SW', 'Sweeper'), ('TA', 'Tactician'), ('TU', 'Turtle'), ('VI', 'Victor')], default='NO', max_length=2)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
