# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Randomdrop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomdrops',
            name='type_special',
            field=models.CharField(choices=[('P', 'Painted'), ('N', 'Normal'), ('C', 'Certified'), ('B', 'Painted/Certified')], default='N', max_length=1),
        ),
    ]
