# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('throwthursday', '0002_auto_20170307_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throw',
            name='matchdone',
            field=models.BooleanField(default=False),
        ),
    ]
